project:
  type: website
  output-dir: docs
  
website:
  title: "Creek Road Craft"
  navbar:
    left:
      - href: index.qmd
        text: Home   
      - wood.qmd
      - stone.qmd
      - cloth.qmd
    

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: false



